language: node_js

node_js:
  - 0.12.2

before_install:
  - ls -l /usr/local/bin/
  - ls -l /usr/local/lib/
  - ls -l /usr/local/etc/
  - npm install -g npm@latest
  - export CHROME_BIN=google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: npm run unit
