language: node_js

node_js:
  - 0.12.2

before_install:
  - echo $PATH
  - ls -l /usr/bin/
  - ls -l /usr/local/
  - npm install -g npm@latest
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: npm run unit
